// This file is automatically generated. Do not edit it directly.
// If you want to use Supabase, uncomment the following lines and add your Supabase URL and API key.
// Or, delete this file if you don't want to use Supabase.
// import { createClient } from '@supabase/supabase-js';

// const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
// const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

// // Import the supabase client like this:
// // import { supabase } from "@/integrations/supabase/client";

// export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

export const supabase = null;
